- docs/tldr.md
> fix step numbering

- src/templates/cromwell/cromwell-aio.template.yaml
- src/templates/cromwell/cromwell-server.template.yaml
Adds ability to select a specific version of Cromwell to be run in the `cromwell-server` stack.
> add cromwell version selection

- src/templates/cromwell/cromwell-aio.template.yaml
fix default value for template root url to match allowed pattern
> fix cfn-lint error

- docs/disclaimer.md
- mkdocs.yml
> Disclaimer

- main.py
- mkdocs.yml
Source code links point to corresponding github blob view
> use github for viewing source

- src/templates/nextflow/nextflow-aio.template.yaml
#18
correctly handle using one bucket
> fix issue #18

- src/containers/nextflow/Dockerfile
- src/containers/nextflow/nextflow.aws.sh
- src/templates/nextflow/nextflow-aio.template.yaml
- src/templates/nextflow/nextflow-resources.template.yaml
resolves #24 
* adds building a nextflow container as part of the nextflow-resources stack
* updates nextflow documentation
> Nextflow updates

- docs/orchestration/nextflow/nextflow-overview.md
update nextflow documentation to align with new CloudFormation template capabilities
> update nextflow documentation

- src/templates/aws-genomics-launch-template.template.yaml
- src/templates/aws-genomics-root-novpc.template.yaml
- src/templates/cromwell/cromwell-aio.template.yaml
- src/templates/nextflow/nextflow-aio.template.yaml
- src/templates/step-functions/sfn-aio.template.yaml
#29 
Makes paths to artifacts user defined parameters.
> resolve Issue 29

- docs/orchestration/nextflow/nextflow-overview.md
- src/containers/nextflow/Dockerfile
- src/containers/nextflow/nextflow.aws.sh
- src/templates/nextflow/nextflow-resources.template.yaml
Updating the nextflow container to pass along parameters to the nextflow executable. This also impacts the way jobs would get submitted to Batch so I've updated the documentation to reflect that. I've also added an nf-core/rnaseq example in the docs demonstrating how to pass parameters.
> Changing Nextflow container to support taking parameters at job submission.

- src/templates/aws-genomics-launch-template.template.yaml
add back ebs-autoscale to step-functions launch template
> fix ecs-additions for step-functions

- src/templates/cromwell/cromwell-aio.template.yaml
Propagate new version selection method to the Cromwell AiO root template.
> propagate cromwell version selection to aio

- src/ebs-autoscale/templates/cloud-init-userdata.yaml
#47 
updates the path to the `ebs-autoscale` tarball
> update path to ebs-autoscale artifact

- src/templates/aws-genomics-launch-template.template.yaml
Fixes scratch mount point override and mapping.
> fix mapping for scratch mount point

- src/templates/aws-genomics-root-novpc.template.yaml
> propagate allowed s3 bucket name pattern

- src/templates/aws-genomics-s3.template.yaml
- src/templates/cromwell/cromwell-aio.template.yaml
- src/templates/nextflow/nextflow-aio.template.yaml
- src/templates/step-functions/sfn-aio.template.yaml
update aio templates:
* remove deprecated parameters
* make default values for parameters consistent
* automatically pick 2 AZs in VPCs
* make stack exports consistent
> update aio templates

- docs/orchestration/nextflow/nextflow-overview.md
- src/containers/nextflow/nextflow.aws.sh
Fixes the regex matching for s3 uri for nextflow projects
> fix s3 project detection

- docs/orchestration/nextflow/nextflow-overview.md
- src/containers/nextflow/nextflow.aws.sh
> fix nextflow s3 project regex

- docs/orchestration/nextflow/nextflow-overview.md
- src/containers/nextflow/nextflow.aws.sh
* add shebang to docs listing
* add EXIT trap
* add additional logging text
> update nextflow entrypoint

- src/templates/aws-genomics-launch-template.template.yaml
add steps missing that are documented here:
https://docs.docker.com/storage/storagedriver/btrfs-driver/
> fix autoexpanding docker data volume

- src/templates/aws-genomics-launch-template.template.yaml
Simplify logic for scratch mount point associated with autoscaling ebs.
> fix scratch mount point mapping

- src/templates/aws-genomics-iam.template.yaml
- src/templates/aws-genomics-launch-template.template.yaml
- src/templates/nextflow/nextflow-aio.template.yaml
allow access to batch workers via SSM sessions to facilitate debugging.
> (re)implement SSM access to batch workers

- src/templates/cromwell/cromwell-server.template.yaml
Add a new S3 open data bucket ARNs parameter and instance profile permission for using shared datasets.
> Add S3 open datasets parameter

- src/templates/nextflow/nextflow-resources.template.yaml
IAM policy SIDs can only have [A-Za-z0-9-]*
> fix iam sids

- docs/core-env/create-custom-compute-resources.md
- src/templates/aws-genomics-launch-template.template.yaml
- src/templates/nextflow/nextflow-resources.template.yaml
* Remove Python 2.7.x dependency since it is now EOL
* Update AWS CLI to v2
* bug fix for nextflow jobrole permissions
> release update

- src/templates/aws-genomics-batch.template.yaml
- src/templates/aws-genomics-launch-template.template.yaml
Fixed the issue of the compute environment not using the "$LATEST" version of a template. 
Fixed in typo with mismatched quotes
> Fix to Launch Template Latest version issue

- README.md
- docs/orchestration/cromwell/cromwell-overview.md
- src/templates/cromwell/cromwell-resources.template.yaml
- Download `womtool` in order for the user to validate input jsons;
- Download `cromshell` to facilitate submission of workflows;
> Add cromwell tools

- src/templates/cromwell/cromwell-resources.template.yaml
https://github.com/aws-samples/aws-genomics-workflows/issues/133
- Add the possibility to pass an s3 file to `CromwellJarUrl`
> add private s3 bucket and add the possibility to gather cromwell from s3

- _scripts/deploy.sh
> remove ASSET_PROFILE from site()

- src/aws-genomics-cdk/examples/batch-bwa-job.json
- src/aws-genomics-cdk/examples/batch-fastqc-job.json
- src/aws-genomics-cdk/examples/batch-gatk-htc.json
- src/aws-genomics-cdk/examples/batch-minimap2-job.json
- src/aws-genomics-cdk/examples/batch-picard-add-missing-groups.json
- src/aws-genomics-cdk/examples/batch-samtools-index.json
- src/aws-genomics-cdk/examples/batch-samtools-sort.json
- src/aws-genomics-cdk/lib/workflows/variant-calling-stack.ts
> change examples source files

- src/templates/cromwell/cromwell-and-core.template.yaml
Create a unified template to launch cromwell and gwf-core
> add cromwell and gwf-core template

- src/templates/gwfcore/gwfcore-root.template.yaml
Adding a message about the location of the S3 bucket. The deployment will fail if the bucket is in another region than the deployment occur.
> add message about s3 bucket location

- src/scripts/nf-aws.py
Add a python helper script for running workflows, monitoring workflow status, and retrieving workflow logs when using Nextflow and batch-squared architecture.
> add nextflow helper script

- src/ecs-additions/provision.sh
* provision.sh
* Also completed a general cleanup of the script (shellcheck was throwing a few errors)
* Add consistency to if statements
* Run shell scripts with 'bash' shebang through bash NOT sh. 
* evaluate and export separately env vars separately
* https://github.com/broadinstitute/cromwell/issues/4687 - see [this comment](https://github.com/broadinstitute/cromwell/issues/4687#issuecomment-662170952)
* https://github.com/aws/amazon-genomics-cli/issues/40
* https://github.com/aws-samples/aws-genomics-workflows/issues/142
*Related issues*
* https://github.com/aws-samples/aws-digital-content-creation-render-environment/issues/13
* https://github.com/aws/amazon-ssm-agent/issues/282
> Remove and reinstall latest versions of amazon ssm agent for alinux2

- .github/workflows/gh-pages.yml
- mkdocs.yml
- requirements.txt
Adds a github workflow for building and deploying docs to Github Pages
> workflow for gh-pages deployment

- src/templates/cromwell/cromwell-resources.template.yaml
- src/templates/gwfcore/gwfcore-root.template.yaml
- add permission to create ECR repo
- declare the use of fsx on cromwell stack
- replace `sub` by `getatt`on output of core stack
> Improvements on FSx integration

- src/templates/gwfcore/gwfcore-root.template.yaml
Make `FSxBucketName` an optional parameter
> FSxBucketName as optional parameter

- docs/orchestration/nextflow/nextflow-trouble-shooting.md
> Improve nextflow docs
