src/templates/aws-genomics-root-novpc.template.yaml, src/templates/aws-genomics-s3.template.yaml, src/templates/cromwell/cromwell-aio.template.yaml
I forgot about naming conventions when I created my bucket name, but it goes through the complete the cloud stack and fails with a naming convention error.
I've added a small prompt:
> The bucket name must respect the S3 bucket naming conventions (can contain lowercase letters, numbers, periods and hyphens).
I also added an `AllowedPattern` and `ConstraintDescription`, but I don't get validation on the form.
The `AllowedPattern` regex comes from the following StackOverflow answer: [Regex for s3 bucket name](https://stackoverflow.com/a/50484916)
```regex
(?=^.{3,63}$)(?!^(\\d+\\.)+\\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$)
```
--- 
By submitting this pull request, I confirm that you can …
=> Add prompt for S3 bucket naming conventions to CloudFormation template

_scripts/configure-deploy.sh
fixes the deployment configuration script - needed to explicitly make the `~/.aws` folder
=> fix deployment config script

src/templates/aws-genomics-s3.template.yaml
The `Type: String` seems to be duplicated so getting a YAMLException in the AWS Designer editor.
=> Remove duplicated Type key from s3 bucket template

_scripts/deploy.sh
uses `s3 sync --delete` instead of `s3 cp --recursive` to deploy site and assets.
this will save space by removing unused assets.
=> use sync --delete for deploy

docs/orchestration/cromwell/cromwell-overview.md
#28 
fixes url to `create-custom-compute-resources` on the Cromwell overview page.
=> fix url to create-custom-compute-resources

src/templates/aws-genomics-batch.template.yaml
#30 
* provide Name tags that allow instances to be quickly identified as
belonging to a specific compute environment in a specific stack
* name compute environments so that they can be quickly identified as
belonging to a specific stack
* name compute environments based on the instances pricing that they
will launch (spot | ondemand)
=> add tagging to batch launched instances

src/templates/aws-genomics-s3.template.yaml, src/templates/cromwell/cromwell-aio.template.yaml, src/templates/nextflow/nextflow-aio.template.yaml, src/templates/step-functions/sfn-aio.template.yaml
Makes supplying the primary bucket name optional.  If left blank, a unique name is generated.  Users can still supply a name that they prefer that complies with S3 bucket naming rules.
=> make s3 data bucket name optional

src/templates/step-functions/sfn-example.template.yaml
parallelize container builds to improve speed of build so that
Lambda time limits aren't breached.
=> optimize codebuid speed

docs/orchestration/nextflow/nextflow-overview.md, src/containers/nextflow/nextflow.aws.sh
Adds an EXIT signal trap to the nextflow container entrypoint script so that workflows that fail emit the correct exit code to Batch but also still preserve the session cache.
Also adds corresponding updates to the docs along with:
* add shebang to docs listing so that folks building from scratch don't omit this
* add additional logging text to stdout to monitor script execution path
=> Add EXIT trap to nextflow entrypoint script

src/templates/nextflow/nextflow-aio.template.yaml
* explicitly stop ecs before starting ebs autoscale on /var/lib/docker
* move nextflow additions to before start ecs
* add steps missing that are documented here: https://docs.docker.com/storage/storagedriver/btrfs-driver/
=> auto expanding docker data volume fixes

src/templates/cromwell/cromwell-server.template.yaml
Let's add the s3:GetObject permission to EC2 instance role for retrieving objects from S3 buckets and open datasets.
=> Add s3:GetObject permission to EC2 instance role

docs/core-env/create-custom-compute-resources.md, src/templates/aws-genomics-launch-template.template.yaml, src/templates/nextflow/nextflow-resources.template.yaml
Update user data to:
- remove installation of Python 2.7 PIP package (Python 2.7 is deprecated)
- install AWS CLI v2 instead of AWS CLI v1
=> Update AWS CLI to v2 and remove Python27

docs/orchestration/nextflow/nextflow-overview.md
The nf-core/rnaseq pipeline that was originally included in this guide for running genomics workflows will not work with the latest version hosted on nf-core. I've modified the guide to pull from the rnaseq-nf example on nextflow.io instead.
=> updating rnaseq demo workflow

docs/orchestration/cromwell/cromwell-overview.md, src/templates/cromwell/cromwell-resources.template.yaml
#120
Add the AWS-managed policy `AmazonSSMManagedInstanceCore` to the EC2InstanceRole. This is necessary to make Session Manager connection work.
=> Add AWS-managed ssm policy to Ec2InstanceRole

src/templates/gwfcore/gwfcore-launch-template.template.yaml
#122
This simply sets an environment variable which will instruct amazon-ecs-agent to only pull images if they are missing from the local cache.
=> Set ECS option to pull docker images only if the image is missing

src/ecs-additions/awscli-shim.sh, src/ecs-additions/ecs-additions-common.sh
Adds a shim that sets LD_LIBRARY_PATH when calling AWS CLI v2. This enables compatibility with containers built using images that lack `glibc`.
=> enable awscli-v2 for containers w/o glibc

src/templates/gwfcore/gwfcore-batch.template.yaml, src/templates/gwfcore/gwfcore-iam.template.yaml, src/templates/gwfcore/gwfcore-launch-template.template.yaml
This PR will help in debugging #114 (or similar provisioning problems), but it is not a solution for the issue.
The purpose of this change is to copy to Cloudwatch logs from container instances which are ephemeral. The problem with troubleshooting provisioning errors is that we currently don't have any insight into what went wrong since we can't see the instance logs. This picks just a few of the logs we'll likely need, and persist those in their own Cloudwatch log group for one week, which should be enough time to investigate an error.
=> Ship logs to cloudwatch to diagnose provisioning errors

src/ecs-additions/ecs-additions-common.sh, src/templates/gwfcore/gwfcore-launch-template.template.yaml
https://github.com/aws-samples/aws-genomics-workflows/issues/124
- Add 4GB of swap space in EC2 instances
=> Add swap space in EC2 instances

src/templates/cromwell/cromwell-resources.template.yaml
https://github.com/aws-samples/aws-genomics-workflows/issues/118
I have moved all the files set up by `cromwell-resources.template.yaml` stored in `/tmp` to `/home/ec2-user`. This is a proposal to start a conversation -- I don't believe the home directory is necessarily the best place, but I do recommend moving all files that should persist out of `/tmp`.
=> Move files from tmp dir to avoid deletion during tmp dir cleanup

src/templates/cromwell/cromwell-resources.template.yaml
- forget to add config4 to cfn-init, so `get_cromwell_tools.sh` was not running
=> run get_cromwell_tools

docs/core-env/setup-aws-batch.md, src/templates/gwfcore/gwfcore-batch.template.yaml
Updates recommended guidance on batch job queue and compute environment configuration. Specifically, the "default" job queue schedules jobs to **only** the "spot" compute environment. Spillover from "spot" to "on-demand" is no longer recommended because of new Batch allocation strategies.
=> update job queue and compute environment guidance

src/templates/cromwell/cromwell-resources.template.yaml
- Add server timeouts parameters to `cromwell.conf`
- S3fs in cromwell sometimes fail to set the region when there are a lot of scatter tasks, so, adding region to `.aws/config` fix this issue
=> Config files

src/containers/nextflow/nextflow.aws.sh, src/ecs-additions/ecs-additions-common.sh, src/templates/gwfcore/gwfcore-launch-template.template.yaml
Fix ability of Nextflow to gracefully cancel workflows when receiving a job termination request from Batch. Specifically, in scenarios where the cleanup process (cancelling pending jobs, preserving session cache) take longer than 10s (the default `docker stop` timeout).
=> Fix graceful cancellation behavior for Nextflow

src/aws-genomics-cdk/lib/workflows/genomics-task-construct.ts, src/aws-genomics-cdk/package-lock.json, src/aws-genomics-cdk/package.json
Bump to CDK v1.102.0 and remove the `jest` dev dependency because of alert on `hosted-git-info@2.8.8`
=> bump to cdk v1.102.0

src/ecs-additions/ecs-additions-common.sh, src/ecs-additions/ecs-logs-collector.sh, src/ecs-additions/provision.sh, src/templates/README.md, src/templates/cromwell/cromwell-resources.template.yaml, src/templates/gwfcore/gwfcore-batch.template.yaml, src/templates/gwfcore/gwfcore-fsx.template.yaml, src/templates/gwfcore/gwfcore-launch-template.template.yaml, src/templates/gwfcore/gwfcore-root.template.yaml
With this PR we are enabling FSx for Lustre deployment and integrating it with cromwell.
High level Changes:
gwfcore-root.template.yaml : Added parameters and resources for handling FSx creation. It also needs the Security Group handling for FSx and Batch.
gwfcore-fsx.template.yaml: the main FSx template which can create SSD/HDD/Scratch type of FSx.
gwfcore-launch-template.template.yaml: handled the bootstraping so that FSx is mounted on the Batch EC2 instances.
gwfcore-batch.template.yaml: Handling FSx Subnets
cromwell-resources.template.yaml: handling mount of FSx and also cromwell jar setup updates.
ecs-additions : This code was updated to correctly handle bootstraping and also to collect logs from the bootstrapping into s3.
=> FSx and Cromwell Updates 

src/templates/cromwell/cromwell-resources.template.yaml, src/templates/gwfcore/gwfcore-batch.template.yaml, src/templates/gwfcore/gwfcore-root.template.yaml
Updated the templates with below : 
- updated cromwell db timeout from 5 secs to 30 secs due to issues faced.
- updated cromwell jar with changes recently made with caching
- added instance type options to config as per other PR raised last year (https://github.com/aws-samples/aws-genomics-workflows/pull/173). Would be helpful to have that option
- added policies for Cromwell EC2 instance to download ECR images.
=> Updated Code to Handle few things

src/ecs-additions/awscli-shim.sh
This is related to issue #146
Add quotes around the `$@` argument in the awscli-shim script. 
Without the quotes, files with spaces in them fail to stage with an error like the one shown in the issue.
With the quotes the command runs properly.
```
./shim.sh s3 ls s3://<bucket>/resources/data/references/barcodes/test\ space/barcode.txt
2022-03-30 12:24:34       1744 barcode.txt
```
=> Fix awscli-shim error when arguments contain a space

src/containers/nextflow/Dockerfile
#199 , #200
Update the Dockerfile for nextflow to account for the upstream base image changing from `alpine` to `amazoncorretto`. The Dockerfile here can now be simplified to just installing the AWS CLI v2 and setting a new entrypoint.
=> Resolve Nextflow build issue

src/templates/gwfcore/gwfcore-root.template.yaml
#196
Remove "n" instance types (e.g. c5n, m5n, r5n) from the default list of instance types.
=> remove 'n' instances from default
